### ISSUE TITLE
Deployment problem for Digital Journey

### ISSUE THREAD

**Issue by jizhaogit** [bcgov/digital-journeys#232]
I tried to do deployment for Digital Journey today and get errors for some cases.

Issue status:

1.	 DEV
        a.	            Web app/api deployment                            Success
        b.	            Camunda deployment                                 Failed
2.	TEST
        a.	            Web app/api deployment                            Failed
        b.	            Camunda deployment                                 Failed
![deployment_Issue_camunda_dev_20220428.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/c3698c0a-ad8e-42cd-b9d4-8dc14207f3b0)![deployment_Issue_camunda_test_20220428.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/47a6c4dc-3f86-41bf-bb5f-316b416b7a2f)![deployment_Issue_web_test_20220428.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/11693d5b-c2bb-409d-96c1-75c187dcb7bf)

**Comment by warrenchristian1telus** [comment]
@jizhaogit The Service account issue should be fixed now.  The latest changes have been deployed to Dev and Test. Please review and let me know if there is any further issue.

**Comment by jizhaogit** [comment]
@warrenchristian1telus  i still get error for doing dev Camunda deployment.  ![deployment_Issue_camunda_dev_20220429.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/a4b4bca2-89db-46b2-b865-61f78e8ca90a)

**Comment by warrenchristian1telus** [comment]
@jizhaogit The namespace issue has been resolved. Deployment looks good on my end now. Please review and let us know if you have any further issues.

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/117ccbfb-d069-4f46-a3b2-74898f3ad767)

**Comment by jizhaogit** [comment]
@warrenchristian1telus   yes the deployment to Camnuda dev is working now!  i will do more testing for web app/api deployment for dev and test site once after they finish the demo. so will hold this ticket till next Monday.    
thank you very much!

**Comment by jizhaogit** [comment]
@kkapoor-fresh @warrenchristian1telus   i just tried Camnuda deployment for test and got error message![deployment_Issue_camunda_test_20220429.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/873ec8d0-a341-4575-b40b-fa9f98db56e7)

**Comment by kkapoor-fresh** [comment]
The deployment is successfull in TEST now but as a permannet solution the "limit.CPU" needs to be increased in the camunda_dc.yaml . I changed it to "1500m" in the pod for deployment to go through. But this needs to be changed in deployment template file so that the value persists in the next build.

**Comment by jizhaogit** [comment]
@kkapoor-fresh   thanks Kunal, i applied the cpu_limit changes from 250m to 1500m in  **.github\workflows\deploy.yaml**.  should that work? please advise. thanks.

**Comment by jizhaogit** [comment]
Hi Kunal, i still get errors for deploying web app/api and Camunda.

**Comment by kkapoor-fresh** [comment]
For camunda you need to modify the deployment templates under /openshift/app for camunda and change the CPU there.
For web , it seems like there is something wrong in this secret BUILD_NAMESPACE: ${{ secrets.BUILD_NAMESPACE }}
Because in TEST, i am seeing the image value being pointed to below in the Deployment configuration resource on openshift
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/forms-flow-web:latest
it should be d89793-test instead, i reckon.

**Comment by warrenchristian1telus** [comment]
@jizhaogit @kkapoor-fresh for the above "in TEST, i am seeing the image value being pointed to below in the Deployment configuration resource on openshift
image: >-
image-registry.openshift-image-registry.svc:5000/test/forms-flow-web:latest
it should be d89793-test instead, i reckon."

I agree, and that's why I tried prepending it in the deployment config earlier. I had also tried updating the secret to ensure it was "d89793-test", but it didn't seem to make any difference. Not sure why the "d89793-" seems to be dropped.

Just to make sure, I've updated it again and re-run the failed deployment to test.

Looks like it worked that time. Ji, can you please verify the latest changes are there?

As for the Camunda deployment, I'm seeing this error:

error: replication controller "forms-flow-bpm-43" has failed progressing

Yet I'm not seeing this in the Builds on tools:

![image](https://user-images.githubusercontent.com/70002196/166340251-a18fa92e-38cf-4be4-94ae-9b44b6657dbe.png)

Or any of the other namespaces.

Kunal, where are these building to? I think it must not be getting that far. The last build I see in tools is from Friday.

Also, shouldn't the log include the actual replaced variables being used? I think it would make things easier to troubleshoot.

![image](https://user-images.githubusercontent.com/70002196/166340762-600de41c-be77-4dcf-b491-5575fea28bd9.png)

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus  to answer your question on camunda builds being built to which namespace. They are being build in tools namespace. I see the last GA run for camunda deployment happened 4 days back only
![image.png](https://images.zenhubusercontent.com/603e7d017ac89a48774c4630/b2d0d38a-1d32-4b7e-b372-4ed924b181fa)

**Comment by warrenchristian1telus** [comment]
Thanks @kkapoor-fresh. I was just wondering because none of the pods for the workflow were showing up. Now I know it's because of the Replication Controller failing to build due to CPU limits.

**Comment by kkapoor-fresh** [comment]
I did a quick filter to get the cpu limits requested for each pod in test namespace.  If we add the individual values, the total comes out to close 7600 m which is in synct with the metrci that we see in the "compute-long-running-quotas" metric on the web console.

**Comment by warrenchristian1telus** [comment]
Sounds good @kkapoor-fresh - let's give that a try then.

Does that mean we just need to adjust CPU_LIMIT in https://github.com/bcgov/digital-journeys/blob/main/.github/workflows/deploy.yaml ?

Should all the pods have the same CPU_LIMIT?

I don't see CPU_LIMIT implemented in: https://github.com/bcgov/digital-journeys/blob/main/.github/workflows/camunda-deploy.yaml - shouldn't it be there as well?

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus CPU_LIMIT for camunda is implemented in https://github.com/bcgov/digital-journeys/blob/main/deployment/openshift/camunda_dc.yaml

It is not necessary to have the CPU_limit same for all the pods. But at least if we can go with the default limits and without facing issues, I am thinking of Production where we are bound to have more than one replicas of the application pods, how helpful will it be for us to be playing around(reducing or increasing) the requested limits by ourself and still running into issues. 

it seems a bit trickier that I thought. I just checked that the CPU requested limits that we are using are either above or equal to the default limits defined for the namespace which is 250m. I am thinking if it is recommended to go below the default limits or should we look at increasing the quota for the namespace.

**Comment by Stella-Archer** [comment]
split into six steps to take CPU load off process
checking this will work then re-automate

**Comment by warrenchristian1telus** [comment]
Deployments have been completed to dev and test environments.

@iman-jamali-fw Can you please verify. If everything looks good, feel free to deploy to production, or let me know and I can run the deployment.

Dev: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form
Test: https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form
Prod: https://digital-journeys.apps.silver.devops.gov.bc.ca/form

Once production updates are verified, please move this to QA.

Also, I was under the impression that there should only be one form in production - Telework Agreement, but I'm also seeing Freedom of Information and Protection of Privacy and New Business License Application. Please remove any forms that shouldn't be there. If we need additional verification on that, please reach out to the scrum team.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh I've identified a couple of issues in the deployment. Test namespace is using images built/deployed there (d89793-test/imagestreams) instead of in tools, and it's out of date, as the builds are going to /tools.

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/9567308c-bcce-4545-9a3f-3e94296e0d2b)

I've manually updated the image to the tools version for the web deployment, but not the other services.

There is also the issue we had in Moodle where dev, test and prod all share the same image, so committed changes will flow through all the environments as pods are cycled. We have no control over what's in dev vs. test and prod.

We will need the builds to be tagged to :dev, :test, :production rather than all to be :latest.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I am suspecting the secret BUILD_NAMESPACE for TEST env in github is pointing to the "test" namespace rathe than the "tools" namespace. We can't see the current secret value but that it seems to be different from the DEV and Prod env. Can we try upda

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh Yes, the BUILD_NAMESPACE likely needs to be updated, but what about the image tags? Right now, dev, test and prod all share an image, so we effectively just have one build possible. TAG_NAME = latest in all builds. Shouldn't TAG_NAME = $NAMESPACE ?

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus this was the intial design when we started working on Digital journeys. We can work in near future on that and I believe that is one of the items in the backlog for PSA.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh Yes, builds are all now going to tools namespace. I think we need to update the DeploymentConfigs for each image to reflect the environment, and avoid images being automatically promoted from dev through to production without approval.

Such as here, in the web_bc.yaml (objects: spec: output: to: name):

https://github.com/bcgov/digital-journeys/blob/064d9ff6186edbbc4ae9190216e90f8037df1125/deployment/openshift/web_bc.yaml#L48

I think rather than name:

'forms-flow-web:latest'

It should be something like:

"forms-flow-web:${{ secrets.NAMESPACE }}"

I know you are busy on getting Performance production-ready, and I don't want to break things here, but let me know what you think. If that seems like a reasonable fix to you, I can give it a try. But I would rather not confuse things if you think it will cause issues, or are planning on deploying a different/better solution.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I also was trying to think of ways to incorporate the tag in the build config. The problem with the above code snippet is that build config will be building buidls to the same namespace which is "tools".  The Secrets.Namepace secret is only available at deployment time as is it gives the namespace where the application will be deployed.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I think we might be able to make use of the github.event.inputs.environment which takes on the value dev , test or prod. We can plug  this expressions in the BUILD_TAG environment variable and pass it as a parameter in the build configuration. 
@freshjwarren

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh @freshjwarren That sounds good to me. In this case, we don't have branches to work with other than main and feature branches. Will we need dev and test branches to make this work? I'd be a bit concerned about having test and prod in different branches, as they could stray from each other and then test won't be a good proxy for testing prod. As long as we can avoid that type of pitfall, I'm good with it. It would also be good to be able to identify the images in tools (to easily see which is which). This could be a :tag, or even in the name: forms-flow-bpm-test-96, etc.
