### ISSUE TITLE
TELEWORK: change supervisorName field to reorder the name

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#362]
**User Story**
As an employee and supervisor I expect the supervisor/manager name should be in the format "Stella Archer" instead of "Archer,Stella". 

**Task**
- [x] Change the order of the name components in the supervisorName field as we did with the employee field. 

**Acceptance Criteria**
- [x]  The name will appear in the order "Stella Archer".

**Comment by iman-jamali-fw** [comment]
@DonMoffatt We need to ask ODS to send us the supervisor's first and last name separately so we can merge them on our backend and send it over to forms. Currently, we are receiving the full name.

Do you know who the right person to ask is?

**Comment by DonMoffatt** [comment]
@T854236 Could you and Justin address what Iman said above? "We need to ask ODS to send us the supervisor's first and last name separately so we can merge them on our backend and send it over to forms. Currently, we are receiving the full name."

**Comment by T854236** [comment]
@DonMoffatt @iman-jamali-fw 

We can split the full name to first and last name with similar logic you have Don.  How do you want to handle middle name?  If we use simple split, it will be part of the first name.

**Comment by DonMoffatt** [comment]
> @DonMoffatt @iman-jamali-fw
> 
> We can split the full name to first and last name with similar logic you have Don. How do you want to handle middle name? If we use simple split, it will be part of the first name.

I think that's fine: e.g. my full name is John Donald Moffatt, so if you want to write it that way, that's fine. Note that on the employee name side we use whatever the person normally goes by, rather than strictly first name (my name appears as "Don Moffatt" rather than "John Moffatt"). That would be ideal, but if you can write it either as "John Moffatt" or "John Donald Moffatt" I think users would be satisfied.  If you have a choice of the latter two options, I would prefer "John Moffatt".

**Comment by DonMoffatt** [comment]
> @DonMoffatt should we then use the existing supervisor_name as the full name but following the format suggested instead of with the comma?

The name for the field is supervisorName but yes, if you could make it look like "Stella Archer" that would save me some trouble in updating Camunda.

**Comment by T854236** [comment]
@DonMoffatt  Changes complete against supervisor_name in the API endpoint.  I believe that is mapped to supervisorName in Camunda.

**Comment by DonMoffatt** [comment]
This looks good - thanks! I will move it to review and have @Stella-Archer  look it tomorrow before we close it. 
![image.png](https://images.zenhubusercontent.com/61e5c6ccd594602905c8af04/a981cc57-ba8f-4115-81e3-e00352bacad5)

**Comment by iman-jamali-fw** [comment]
Thank you @T854236 ! this is great!
I was wondering if you can do the same change for the `name` field. We merged the first and last name on our backend under a new name (displayName). This caused some issues, since we need to change the name of that field in a few places in Camunda and form scripts (haven't done that yet). Can you please change the format of `name` similar to what you did for the supervisor's name?

@DonMoffatt This would make the form workflow runs as before, we just need to change the API name of Employee Name back to `name`.

**Comment by DonMoffatt** [comment]
> Thank you @T854236 ! this is great! I was wondering if you can do the same change for the `name` field. We merged the first and last name on our backend under a new name (displayName). This caused some issues, since we need to change the name of that field in a few places in Camunda and form scripts (haven't done that yet). Can you please change the format of `name` similar to what you did for the supervisor's name?
> 
> @DonMoffatt This would make the form workflow runs as before, we just need to change the API name of Employee Name back to `name`.

I updated the Camunda workflow to use displayName and uploaded it a short time ago. @iman-jamali-fw  Should I change it back to "name"? In any case, email still isn't working (I am not being sent a copy of my submission).

**Comment by DonMoffatt** [comment]
I will hold off and leave it as displayName unless otherwise directed. It would be easy enough to swap "name" back in, however. I am also concerned about introducing versioning issues with the workflow if others are updating it for other reasons. I am more concerned about why I didn't receive an email, however.

**Comment by T854236** [comment]
@iman-jamali-fw @DonMoffatt 

Same logic applied to the name column in DEV.  Please review.

**Comment by DonMoffatt** [comment]
> @iman-jamali-fw @DonMoffatt
> 
> Same logic applied to the name column in DEV. Please review.

Thanks @T854236 - should I change the field back to "name" on both the form and workflow? Easily done - just let me know.

**Comment by DonMoffatt** [comment]
> Great! Thank you @T854236
> 
> @DonMoffatt Yes please change it back to "name" on the form and workflow. It should then work on DEV and TEST.
> 
> Once everything was OK please let @T854236 know to make the same change for PROD. Thank you

I've made the changes and the fields fill correctly (yay!) but I still don't get a copy.

**Comment by iman-jamali-fw** [comment]
Thank you @DonMoffatt 
I'll look into it and update you.

**Comment by iman-jamali-fw** [comment]
@DonMoffatt Workflow works again on DEV. 
The cause of the issue was that Telework had no workflow assigned to it. This probably happened after the form was updated. 

![Screen Shot 2022-06-22 at 2.39.35 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/75317037-7f3f-4e57-b50e-28b343985364)

**Comment by DonMoffatt** [comment]
@iman-jamali-fw  That would do it!

**Comment by Stella-Archer** [comment]
works great thanks!
